title = 'Freifunk Berlin'
languageCode = 'de'
baseURL = 'https://berlin.freifunk.net/'

theme = "ananke"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

SectionPagesMenu = "main"
enableRobotsTXT = true

[languages]
    [languages.de]
	weight = 1
        languageName = "Deutsch"
        languageCode = "de"
        title = "Freifunk Berlin"	
    [languages.en]
        weight = 2
        languageName = "English"
        languageCode = "en"
        title = "Freifunk Berlin"

[sitemap]
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-white"
  # recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/freifunk_berlin"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/freifunk-berlin"
