title = 'Freifunk Berlin'
languageCode = 'de'

baseURL = "https://berlin.freifunk.net"

[module]
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

SectionPagesMenu = "main"
enableRobotsTXT = true

timeout = "120s"

disableKinds = ['taxonomy', 'term']

[languages]
    [languages.de]
	weight = 1
        languageName = "Deutsch"
        languageCode = "de"
        title = "Freifunk Berlin"	
    [languages.en]
        weight = 2
        languageName = "English"
        languageCode = "en"
        title = "Freifunk Berlin"

[sitemap]
  filename = "sitemap.xml"

[params.docs]
themeColor = "red"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.primary]]
    name  = "Docs"
    url = "docs/"
    identifier = "docs"
    weight = 10

[[menu.primary]]
    name  = "Showcase"
    url = "/showcase"
    identifier = "showcase"
    weight = 20

[[menu.primary]]
    name  = "Community"
    url = "https://github.com/colinwilson/lotusdocs/discussions"
    identifier = "community"
    weight = 30

[params.footer]
copyright = "This work is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) | [Imprint](/impressum)"
version = true

[params.social]
github = "freifunk-berlin/"
twitter = "freifunk_berlin"