title = 'Freifunk Berlin'
languageCode = 'de'

baseURL = "https://berlin.freifunk.net"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

enableRobotsTXT = true
enableGitInfo = true

timeout = "120s"

disableKinds = ['taxonomy', 'term']

[module]
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false
    [[module.mounts]]
        disableWatch = false
        lang = ''
        source = 'node_modules'
        target = 'assets'
    [[module.mounts]]
        disableWatch = false
        lang = ''
        source = 'assets'
        target = 'assets'

[languages]
    [languages.de]
        weight = 1
        languageName = "Deutsch"
        languageCode = "de"
        title = "Freifunk Berlin"
        [languages.de.menus]
            [[languages.de.menus.primary]]
                name = 'Mitmachen'
                url = "participate/"
                weight = 10
            [[languages.de.menus.primary]]
                name = 'Netzkarte'
                url = 'map/'
                weight = 20
            [[languages.de.menus.primary]]
                name = 'Spenden'
                url = 'donate/'
                weight = 20
            [[languages.de.menus.primary]]
                name = 'Dokumentation'
                url = 'docs/'
                weight = 40
            [[languages.de.menus.primary]]
                name = 'Downloads'
                url = 'downloads/'
                weight = 50
            [[languages.de.menus.primary]]
                name = 'Kontakt'
                url = 'contact/'
                weight = 70
        [languages.de.params]
            description = "Freifunk Berlin ist eine lokale Initiative mit dem Ziel, ein freies WLAN-Netzwerk über Berlin aufzuspannen und freien Netzzugang anzubieten."
            errordescription = "Die gesuchte Seite konnte nicht gefunden werden. Versuche es später noch einmal oder gehe zurück zu unserer Homepage."
            errortitle = "Seite nicht gefunden :("
            [languages.de.params.footer]
                copyright = ":YEAR: Freifunk Berlin | [Impressum](/de/imprint)"
                version = true
                [[languages.de.params.footer.link]]
                    name = "Impressum"
                    url = "/de/imprint/"
            [languages.de.params.actions]
                [languages.de.params.actions.primary]
                    name="Freies WLAN finden"
                    url="map/"
                [languages.de.params.actions.seconary]
                    name="Freifunker*in werden"
                    url="participate/"
    [languages.en]
        weight = 2
        languageName = "English"
        languageCode = "en"
        title = "Freifunk Berlin"
        [languages.en.menus]
            [[languages.en.menus.primary]]
                name = 'Participate'
                url = "participate/"
                weight = 10
            [[languages.en.menus.primary]]
                name = 'Map'
                url = 'map/'
                weight = 20
            [[languages.en.menus.primary]]
                name = 'Donate'
                url = 'donate/'
                weight = 30
            [[languages.en.menus.primary]]
                name = 'Documentation'
                url = 'docs/'
                weight = 40
            [[languages.en.menus.primary]]
                name = 'Downloads'
                url = 'downloads/'
                weight = 50
            [[languages.en.menus.primary]]
                name = 'Contact'
                url = 'contact/'
                weight = 70
        [languages.en.params]
            description = "Freifunk Berlin is a local initiative with the aim of setting up a free WiFi network across Berlin and offering free network access."
            errordescription = "The requested site could not be found. Please try again later or return to our homepage."
            errortitle = "Site not found :("
            [languages.en.params.footer]
                copyright = ":YEAR: Freifunk Berlin | [imprint](/de/imprint)"
                version = true
                [[languages.en.params.footer.link]]
                    name = "Imprint"
                    url = "/de/imprint/"
            [languages.en.params.actions]
                [languages.en.params.actions.primary]
                    name="Find free WiFi"
                    url="map/"
                [languages.en.params.actions.seconary]
                    name="Become part of Freifunk"
                    url="participate/"

[sitemap]
    filename = "sitemap.xml"

[markup.goldmark.renderer]
    unsafe = true

[params]
    sans_serif_font = "Arial"
    secondary_font  = "Arial"
    mono_font       = "Courier New"
    primary = "#dc0067"
    editURL = "https://github.com/freifunk-berlin/berlin.freifunk.net/edit/main/content"
    [params.social]
        github = "freifunk-berlin/"
        mastodon = "https://chaos.social/@freifunk_berlin"
    [params.docs]
        themeColor = "ff_blue"
        title = "FF-Berlin Docs"
        prism = true
        repoURL         = "https://github.com/freifunk-berlin/berlin.freifunk.net"
        repoBranch      = "main"
        editPage        = true
        lastMod         = true
        lastModRelative = true
        sidebarIcons    = true
        titleIcon       = true
        listDescTrunc   = 100
        descriptions    = true
    [params.flexsearch]
[build]
  writeStats = true
