---
name: Deploy website to dev server

on:    # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.2'
          extended: true

      - name: Build
        env:
          HUGO_ENV: production
          HUGO_MATRIX_ACCESS_TOKEN: ${{ secrets.HUGO_MATRIX_ACCESS_TOKEN }}
          HUGO_MATRIX_HOME_SERVER: ${{ secrets.HUGO_MATRIX_HOME_SERVER }}
          HUGO_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL_DEVELOPMENT: ${{ vars.URL_DEVELOPMENT }}
        run: hugo --minify -b "$URL_DEVELOPMENT/$GITHUB_REF_NAME" --destination "branch/$GITHUB_REF_NAME"

      - name: Create robots.txt
        run: 'echo -e "User-agent: *\nDisallow: /" > branch/robots.txt'

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.IP_DEVELOPMENT }}
          username: ${{ secrets.SSH_USERNAME_DEVELOPMENT }}
          key: ${{ secrets.SSH_KEY_DEVELOPMENT }}
          source: "branch/${{ github.ref_name }}"
          target: ${{ vars.WEBROOT_DEVELOPMENT}}
          strip_components: 1
